from typing import Tuple
import pandas as pd

# 277 jogos para simular
PREVIOUS_MATCHES = {
  'Flamengo': {
    'Internacional': (1,1),
    'Cruzeiro': (2,0),
    'Remo': (3,0),
    'Santos': (3,1),
    'EC Bahia': (2,0),
    'Vasco da Gama': (2,2),
    'Palmeiras': (0,3),
    'São Paulo': (1,1),
    'EC Vitória': (2,0),
    'Botafogo': (3,0),
    'Mirassol': (2,0),
    'Corinthians': (2,1),
    'RB Bragantino': (2,1),
  },
  'Palmeiras': {
    'EC Vitória': (5,1),
    'Fluminense': (2,1),
    'Mirassol': (1,0),
    'Botafogo': (2,1),
    'Grêmio': (2,1),
    'Athletico-PR': (1,0),
    'Santos': (1,1),
    'Cruzeiro': (1,1),
    'Chapecoense': (1,0),
    'Atlético-MG': (1,2),
    'Internacional': (0,0),
    'Vasco da Gama': (4,1),
    'São Paulo': (2,0),
  }, 
  'Athletico-PR': {
    'Santos': (2,1),
    'Corinthians': (0,1),
    'Cruzeiro': (2,1),
    'Coritiba FC': (2,0),
    'Botafogo': (4,1),
    'Chapecoense': (2,0),
    'EC Vitória': (3,1),
    'Grêmio': (0,0),
    'Flamengo': (1,1),
    'Mirassol': (1,0),
    'Internacional': (2,0),
    'RB Bragantino': (1,1),
    'Fluminense': (3,3),
    'EC Bahia': (2,1),
  }, 
  'Fluminense': {
    'Grêmio': (2,1),
    'Botafogo': (1,0),
    'Athletico-PR': (3,2),
    'Atlético-MG': (1,0),
    'Corinthians': (3,1),
    'Flamengo': (1,2),
    'Chapecoense': (2,1),
    'EC Vitória': (2,2),
    'São Paulo': (2,1),
    'RB Bragantino': (1,1),
    'EC Bahia': (0,0),
    'Vasco da Gama': (1,0),
    'Remo': (2,1),
    'Palmeiras': (3,2),
  }, 
  'EC Bahia': {
    'Fluminense': (1,1),
    'EC Vitória': (1,1),
    'RB Bragantino': (2,0),
    'Athletico-PR': (3,0),
    'Palmeiras': (1,2),
    'Santos': (2,2),
    'Cruzeiro': (1,2),
    'Grêmio': (1,1),
    'Botafogo': (2,1),
    'Chapecoense': (2,0),
    'Corinthians': (1,1),
    'Vasco da Gama': (0,0),
    'Internacional': (3,2),
    'Remo': (2,1),
  }, 
  'Cruzeiro': {
    'Coritiba FC': (1,2),
    'Corinthians': (1,1),
    'Vasco da Gama': (3,3),
    'Santos': (0,0),
    'EC Vitória': (3,0),
    'RB Bragantino': (2,1),
    'Grêmio': (2,0),
    'Atlético-MG': (1,3),
    'Chapecoense': (2,1),
    'Fluminense': (1,1),
    'Botafogo': (0,1),
    'Mirassol': (3,1),
    'Athletico-PR': (3,1),
    'Flamengo': (2,1),
  }, 
  'Atlético-MG': {
    'Palmeiras': (2,2),
    'Remo': (3,3),
    'Internacional': (1,0),
    'São Paulo': (1,0),
    'Athletico-PR': (2,1),
    'Flamengo': (0,4),
    'Botafogo': (1,1),
    'Mirassol': (3,1),
    'EC Bahia': (1,1),
    'Grêmio': (3,0),
    'EC Vitória': (2,1),
    'Fluminense': (3,1),
    'Chapecoense': (1,1),
  }, 
  'Santos': {
    'São Paulo': (1,1),
    'Vasco da Gama': (2,1),
    'Corinthians': (1,1),
    'Internacional': (1,2),
    'Remo': (2,0),
    'Atlético-MG': (1,0),
    'Fluminense': (2,3),
    'RB Bragantino': (2,0),
    'Coritiba FC': (0,3),
    'EC Vitória': (3,1),
    'Chapecoense': (2,2),
    'Athletico-PR': (0,2),
    'Mirassol': (1,1),
    'Cruzeiro': (2,1),
  }, 
  'Coritiba FC': {
    'RB Bragantino': (0,1),
    'São Paulo': (0,1),
    'Remo': (1,0),
    'Vasco da Gama': (1,1),
    'Fluminense': (1,1),
    'Atlético-MG': (2,0),
    'Internacional': (2,2),
    'EC Bahia': (3,2),
    'Flamengo': (3,0),
    'Palmeiras': (1,3),
    'Cruzeiro': (0,1),
    'Chapecoense': (2,1),
    'Corinthians': (2,1),
    'Mirassol': (1,2),
    'Athletico-PR': (3,3),
  }, 
  'RB Bragantino': {
    'Atlético-MG': (1,0),
    'Athletico-PR': (1,1),
    'São Paulo': (1,2),
    'Botafogo': (1,2),
    'Flamengo': (3,0),
    'Remo': (4,2),
    'Palmeiras': (0,1),
    'Grêmio': (1,0),
    'EC Vitória': (2,0),
    'Internacional': (3,1),
    'Coritiba FC': (0,0),
    'Corinthians': (0,2),
    'EC Bahia': (2,3),
  }, 
  'São Paulo': {
    'Flamengo': (2,1),
    'Grêmio': (2,0),
    'Chapecoense': (2,0),
    'Palmeiras': (0,1),
    'Cruzeiro': (4,1),
    'Mirassol': (1,0),
    'EC Bahia': (2,2),
    'Botafogo': (1,1),
    'Athletico-PR': (1,2),
    'Coritiba FC': (1,1),
    'RB Bragantino': (2,1),
    'Atlético-MG': (2,0),
    'Internacional': (1,0),
  }, 
  'Botafogo': {
    'Cruzeiro': (4,0),
    'Flamengo': (0,3),
    'Mirassol': (3,2),
    'Coritiba FC': (2,2),
    'Internacional': (2,2),
    'Remo': (1,2),
    'Corinthians': (3,1),
    'Santos': (2,1),
    'EC Vitória': (0,0),
    'Fluminense': (1,1),
    'Athletico-PR': (2,3),
    'Palmeiras': (0,0),
    'RB Bragantino': (1,1),
    'Grêmio': (3,2),
  },
  'EC Vitória': {
    'Remo': (2,0),
    'Flamengo': (1,2),
    'Atlético-MG': (2,0),
    'Mirassol': (1,0),
    'São Paulo': (2,0),
    'Corinthians': (0,0),
    'Coritiba FC': (4,1),
    'Internacional': (2,0),
    'Vasco da Gama': (1,0),
    'Palmeiras': (0,4),
    'Botafogo': (1,0),
    'EC Bahia': (0,2),
    'Grêmio': (1,0),
    'Cruzeiro': (1,3),
  }, 
  'Corinthians': {
    'EC Bahia': (1,2),
    'RB Bragantino': (2,0),
    'Coritiba FC': (0,2),
    'Flamengo': (1,1),
    'Internacional': (0,1),
    'Palmeiras': (0,0),
    'Vasco da Gama': (1,0),
    'São Paulo': (3,2),
    'Atlético-MG': (1,0),
    'Remo': (3,0),
    'Athletico-PR': (0,0),
    'Cruzeiro': (1,2),
    'Santos': (0,1),
    'Chapecoense': (1,2),
    'Fluminense': (1,3),
  }, 
  'Mirassol': {
    'Vasco da Gama': (2,1),
    'Cruzeiro': (2,2),
    'Santos': (2,2),
    'Coritiba FC': (0,1),
    'RB Bragantino': (0,1),
    'EC Bahia': (1,2),
    'Corinthians': (2,1),
    'Chapecoense': (1,1),
    'Fluminense': (1,0),
    'Grêmio': (2,1),
    'Palmeiras': (1,1),
    'Remo': (2,1),
    'Flamengo': (1,5),
    'EC Vitória': (2,2),
    'Botafogo': (2,0),
  }, 
  'Vasco da Gama': {
    'Chapecoense': (1,1),
    'EC Bahia': (0,1),
    'Palmeiras': (2,1),
    'Fluminense': (3,2),
    'Grêmio': (2,1),
    'Botafogo': (1,2),
    'São Paulo': (2,1),
    'Athletico-PR': (1,0),
    'RB Bragantino': (0,3),
    'Atlético-MG': (0,1),
    'Mirassol': (1,1),
    'Santos': (0,3),
    'Cruzeiro': (3,1),
    'Coritiba FC': (5,0),
  }, 
  'Grêmio': {
    'Botafogo': (5,3),
    'Atlético-MG': (2,1),
    'RB Bragantino': (1,1),
    'Remo': (0,0),
    'Coritiba FC': (1,0),
    'Flamengo': (0,1),
    'Santos': (3,2),
    'Corinthians': (1,3),
    'Fluminense': (1,1),
    'São Paulo': (2,1),
    'Chapecoense': (3,1),
    'Vasco da Gama': (1,2),
    'Palmeiras': (0,0),
  }, 
  'Internacional': {
    'Athletico-PR': (0,1),
    'Palmeiras': (1,3),
    'EC Bahia': (0,1),
    'Chapecoense': (2,0),
    'São Paulo': (1,1),
    'Grêmio': (0,0),
    'Mirassol': (1,2),
    'Fluminense': (2,0),
    'Vasco da Gama': (4,1),
    'Cruzeiro': (1,2),
    'Flamengo': (1,1),
    'Atlético-MG': (0,0),
    'Remo': (1,1),
    'Santos': (2,3),
  }, 
  'Remo': {
    'Mirassol': (2,2),
    'Internacional': (1,1),
    'Fluminense': (0,2),
    'EC Vitória': (2,0),
    'EC Bahia': (4,1),
    'Vasco da Gama': (1,1),
    'Cruzeiro': (0,1),
    'Palmeiras': (1,1),
    'Athletico-PR': (1,2),
    'São Paulo': (1,0),
    'EC Vitória': (2,0),
    'Atlético-MG': (2,2),
    'Coritiba FC': (2,3),
    'Flamengo': (0,1),
    'Santos': (1,2),
  }, 
  'Chapecoense': {
    'Santos': (4,2),
    'Coritiba FC': (3,3),
    'Grêmio': (1,1),
    'Corinthians': (0,0),
    'Atlético-MG': (0,4),
    'EC Vitória': (1,1),
    'Botafogo': (1,4),
    'RB Bragantino': (1,2),
    'Remo': (2,3),
    'Flamengo': (0,4),
    'EC Bahia': (3,3),
    'São Paulo': (1,0),
    'Internacional': (1,2),
  }
}

def tabela_zerada():
  return pd.DataFrame({
    'nome': ['Flamengo', 'Palmeiras', 'Athletico-PR', 'Fluminense', 'EC Bahia', 'Cruzeiro', 'Atlético-MG', 'Santos', 'Coritiba FC', 
             'RB Bragantino', 'São Paulo', 'Botafogo', 'EC Vitória', 'Corinthians', 'Mirassol', 'Vasco da Gama', 'Grêmio', 'Internacional', 
             'Remo', 'Chapecoense'],
    'pontos': [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    'saldo_gols': [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    'gols_feitos': [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
  })

def match_score(time1_name, time2_name)->Tuple[int,int]|None:
  return PREVIOUS_MATCHES[time1_name].get(time2_name, None)
